### ISSUE TITLE
Install both vfg-field-array and vfg-field-object

### ISSUE THREAD

**Issue by kahunacoder** [gwenaelp/vfg-field-array#6]
In the following example:
```With container component and object as array item```

You are using vfg-field-array and vfg-field-object. How do you install both? The docs say to do this in the main.js file

```import ModuleLibrary from 'vfg-field-array'```
```Vue.use(ModuleLibrary);```

and 
```import ModuleLibrary from 'vfg-field-object';```
```Vue.use(ModuleLibrary);```

How do you use both?

**Comment by gwenaelp** [comment]
You need to implement your schema this way (this is just an example) :

```
{
    fields: [{
      type: 'array',
      label: 'Columns',
      model: 'columns',
      itemContainerComponent: 'AComponent', //optional
      showRemoveButton: false, //optional
      fieldClasses: 'arrayEditor', //optional
      newElementButtonLabelClasses: 'button is-primary', //optional
      items: {
        type: 'object',
        default: {},
        schema: {
          fields: [{
            type: 'input',
            label: 'Label',
            model: 'label',
          }, {
            type: 'input',
            label: 'Field',
            model: 'field',
          }],
        },
      },
    }],
  }
```

Does this answers your question?

**Comment by kahunacoder** [comment]
No, my problem is with installing both modules into my main.js file.

**Comment by kahunacoder** [comment]
import ModuleLibrary from 'vfg-field-array'
Vue.use(ModuleLibrary);

and
import ModuleLibrary from 'vfg-field-object';
Vue.use(ModuleLibrary)

Both modules are called ModuleLibrary

**Comment by gwenaelp** [comment]
Ah ok.

I think I need to change those README.

Actually you can name "ModuleLibrary" whatever you want:

```
import VfgFieldArray from 'vfg-field-array'
Vue.use(VfgFieldArray);
```
and
```
import VfgFieldObject from 'vfg-field-object';
Vue.use(VfgFieldObject)
```

This "ModuleLibrary" name is just a variable you instanciate with the import.
Is it more clear? Tell me, to know if I can close the issue.

**Comment by kahunacoder** [comment]
Thank you that is what I needed to understand.
